# Generated by Django 4.2.5 on 2023-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('objective', models.CharField(max_length=1000)),
                ('linkin', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AwardsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EducationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('cgpa', models.CharField(max_length=500)),
                ('pyear', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('edate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=1000)),
                ('othersinterest', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=500)),
                ('workflow', models.CharField(max_length=500)),
                ('wfone', models.CharField(max_length=500)),
                ('wftwo', models.CharField(max_length=500)),
                ('wfthree', models.CharField(max_length=500)),
                ('wffour', models.CharField(max_length=500)),
                ('wffive', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='No images', upload_to='images/')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
